name = "microbit_accel"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["microbit_accel"]

[[depends-on]]
microbit_bsp = "~0.2.0"

[build-profiles]
"*" = "development"

[gpr-set-externals]
MICROBIT_BSP_COMPILE_CHECKS="enabled"
MICROBIT_BSP_RUNTIME_CHECKS="enabled"
MICROBIT_BSP_STYLE_CHECKS="disabled"
MICROBIT_BSP_CONTRACTS="enabled"
MICROBIT_BSP_BUILD_MODE="debug"

ADL_MIDDLEWARE_COMPILE_CHECKS="enabled"
ADL_MIDDLEWARE_RUNTIME_CHECKS="enabled"
ADL_MIDDLEWARE_STYLE_CHECKS="disabled"
ADL_MIDDLEWARE_CONTRACTS="enabled"
ADL_MIDDLEWARE_BUILD_MODE="debug"

EMBEDDED_COMPONENTS_COMPILE_CHECKS="enabled"
EMBEDDED_COMPONENTS_RUNTIME_CHECKS="enabled"
EMBEDDED_COMPONENTS_STYLE_CHECKS="disabled"
EMBEDDED_COMPONENTS_CONTRACTS="enabled"
EMBEDDED_COMPONENTS_BUILD_MODE="debug"
