name = "microbit_accel"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["microbit_accel"]

[[depends-on]]
microbit_bsp = "~0.2.0"

[build-profiles]
"*" = "development"

[gpr-set-externals]
ADL_MIDDLEWARE_COMPILE_CHECKS="enabled"
ADL_MIDDLEWARE_RUNTIME_CHECKS="enabled"
ADL_MIDDLEWARE_STYLE_CHECKS="disabled"
ADL_MIDDLEWARE_CONTRACTS="enabled"
ADL_MIDDLEWARE_BUILD_MODE="debug"

[[pins]]
microbit_bsp = { url='https://github.com/JeremyGrosser/microbit_bsp' }
